forward CarregandoCarros();
public CarregandoCarros()
{
	new b[256];
	new rows,fields;
	cache_get_data(rows, fields);
	new totalcarros = rows;
 	for(new i; i < totalcarros; i++)
  	{
  	    cache_get_field_content(i,"id",b);					VehicleInfo[i][vID] = strval(b);
		cache_get_field_content(i,"model",b);				VehicleInfo[i][vModel] = strval(b);
		if(VehicleInfo[i][vModel] < 400) VehicleInfo[i][vModel] = 481;
		if(IsInvalidVehicle(VehicleInfo[i][vModel])) VehicleInfo[i][vModel] = 481;

		cache_get_field_content(i,"spawn_x",b);				VehicleInfo[i][vSpawnX] = floatstr(b);
		cache_get_field_content(i,"spawn_y",b);				VehicleInfo[i][vSpawnY] = floatstr(b);
		cache_get_field_content(i,"spawn_z",b);				VehicleInfo[i][vSpawnZ] = floatstr(b);
		cache_get_field_content(i,"spawn_r",b);				VehicleInfo[i][vSpawnR] = floatstr(b);
		cache_get_field_content(i,"color1",b);				VehicleInfo[i][vColor1] = strval(b);
		cache_get_field_content(i,"color2",b);				VehicleInfo[i][vColor2] = strval(b);
		cache_get_field_content(i,"owning_character",b);	VehicleInfo[i][vOwner] = strval(b);
		cache_get_field_content(i,"mileage",b);				VehicleInfo[i][vMileage] = strval(b);
		cache_get_field_content(i,"lock",b);				VehicleInfo[i][vLock] = strval(b);
		cache_get_field_content(i,"locked",b);				VehicleInfo[i][vLocked] = strval(b);
		cache_get_field_content(i,"times_destroyed",b);		VehicleInfo[i][vDestroyed] = strval(b);
		cache_get_field_content(i,"fuel",b);				VehicleInfo[i][vFuel] = strval(b);
		cache_get_field_content(i,"faction",b);				VehicleInfo[i][vFaction] = strval(b);
		cache_get_field_content(i,"owner_name",b);			format(VehicleInfo[i][vOwnerName],MAX_PLAYER_NAME,"%s",b);
		VehicleInfo[i][vEngine] = 0;
        cache_get_field_content(i,"death_time",b);			VehicleInfo[i][vDeathTime] = strval(b);
        cache_get_field_content(i,"plate",b);				format(VehicleInfo[i][vPlate],32,"%s",b);
        cache_get_field_content(i,"insurance",b);			VehicleInfo[i][vInsurance] = strval(b);
        cache_get_field_content(i,"mods",b);				format(VehicleInfo[i][vMods],256,"%s",b);
        cache_get_field_content(i,"paintjob",b);			VehicleInfo[i][vPaintjob] = strval(b);
        cache_get_field_content(i,"imp",b);					VehicleInfo[i][vImpounded] = strval(b);
		cache_get_field_content(i,"gps",b);					VehicleInfo[i][vGps] = strval(b);
        cache_get_field_content(i,"comp",b);				VehicleInfo[i][vCompany] = strval(b);
		cache_get_field_content(i,"dmg1",b);				VehicleInfo[i][vDamage][0] = strval(b);
		cache_get_field_content(i,"dmg2",b);				VehicleInfo[i][vDamage][1] = strval(b);
		cache_get_field_content(i,"dmg3",b);				VehicleInfo[i][vDamage][2] = strval(b);
		cache_get_field_content(i,"dmg4",b);				VehicleInfo[i][vDamage][3] = strval(b);
        cache_get_field_content(i,"hp",b);					VehicleInfo[i][vHealth] = floatstr(b);
        cache_get_field_content(i,"neon",b);				VehicleInfo[i][vNeon] = strval(b);
        cache_get_field_content(i,"immob",b);				VehicleInfo[i][vImmob] = strval(b);
        cache_get_field_content(i,"selling",b);				VehicleInfo[i][vSelling] = strval(b);
        if(!strlen(VehicleInfo[i][vPlate]) && VehicleInfo[i][vModel]) FetchVehiclePlate(i,VehicleInfo[i][vPlate]);
        cache_get_field_content(i,"sprice",b);				VehicleInfo[i][vSellingPrice] = strval(b);
        cache_get_field_content(i,"sexpire",b);				VehicleInfo[i][vSellingExpire] = strval(b);
        cache_get_field_content(i,"radio",b);				VehicleInfo[i][vRadio] = strval(b);
        cache_get_field_content(i,"world",b);				VehicleInfo[i][vWorld] = strval(b);
        cache_get_field_content(i,"interior",b);			VehicleInfo[i][vInterior] = strval(b);
        cache_get_field_content(i,"malotes",b);				VehicleInfo[i][vMalote] = strval(b);
		cache_get_field_content(i,"slottipo1",b);				VehicleInfo[i][vSlotTipo1] = strval(b);
	    cache_get_field_content(i,"slottipo2",b);				VehicleInfo[i][vSlotTipo2] = strval(b);
	    cache_get_field_content(i,"slottipo3",b);				VehicleInfo[i][vSlotTipo3] = strval(b);
	    cache_get_field_content(i,"slottipo4",b);				VehicleInfo[i][vSlotTipo4] = strval(b);
	    cache_get_field_content(i,"slottipo5",b);				VehicleInfo[i][vSlotTipo5] = strval(b);
	    cache_get_field_content(i,"slottipo6",b);				VehicleInfo[i][vSlotTipo6] = strval(b);
	    cache_get_field_content(i,"slottipo7",b);				VehicleInfo[i][vSlotTipo7] = strval(b);
	    cache_get_field_content(i,"slottipo8",b);				VehicleInfo[i][vSlotTipo8] = strval(b);
	    cache_get_field_content(i,"slottipo9",b);				VehicleInfo[i][vSlotTipo9] = strval(b);
	    cache_get_field_content(i,"slottipo10",b);				VehicleInfo[i][vSlotTipo10] = strval(b);
	    cache_get_field_content(i,"slot1",b);				VehicleInfo[i][vSlot1] = strval(b);
	    cache_get_field_content(i,"slot2",b);				VehicleInfo[i][vSlot2] = strval(b);
	    cache_get_field_content(i,"slot3",b);				VehicleInfo[i][vSlot3] = strval(b);
	    cache_get_field_content(i,"slot4",b);				VehicleInfo[i][vSlot4] = strval(b);
		cache_get_field_content(i,"slot5",b);				VehicleInfo[i][vSlot5] = strval(b);
		cache_get_field_content(i,"slot6",b);				VehicleInfo[i][vSlot6] = strval(b);
		cache_get_field_content(i,"slot7",b);				VehicleInfo[i][vSlot7] = strval(b);
		cache_get_field_content(i,"slot8",b);				VehicleInfo[i][vSlot8] = strval(b);
		cache_get_field_content(i,"slot9",b);				VehicleInfo[i][vSlot9] = strval(b);
		cache_get_field_content(i,"slot10",b);				VehicleInfo[i][vSlot10] = strval(b);
		cache_get_field_content(i,"ammo1",b);				VehicleInfo[i][vAmmo1] = strval(b);
		cache_get_field_content(i,"ammo2",b);				VehicleInfo[i][vAmmo2] = strval(b);
		cache_get_field_content(i,"ammo3",b);				VehicleInfo[i][vAmmo3] = strval(b);
		cache_get_field_content(i,"ammo4",b);				VehicleInfo[i][vAmmo4] = strval(b);
		cache_get_field_content(i,"ammo5",b);				VehicleInfo[i][vAmmo5] = strval(b);
		cache_get_field_content(i,"ammo6",b);				VehicleInfo[i][vAmmo6] = strval(b);
		cache_get_field_content(i,"ammo7",b);				VehicleInfo[i][vAmmo7] = strval(b);
		cache_get_field_content(i,"ammo8",b);				VehicleInfo[i][vAmmo8] = strval(b);
		cache_get_field_content(i,"ammo9",b);				VehicleInfo[i][vAmmo9] = strval(b);
		cache_get_field_content(i,"ammo10",b);				VehicleInfo[i][vAmmo10] = strval(b);
		cache_get_field_content(i,"motor",b);				VehicleInfo[i][vMotor] = floatstr(b);
		cache_get_field_content(i,"bateria",b);				VehicleInfo[i][vBateria] = floatstr(b);
		cache_get_field_content(i,"pluva1",b);				VehicleInfo[i][vpluva1] = strval(b);
		cache_get_field_content(i,"pluva2",b);				VehicleInfo[i][vpluva2] = strval(b);
		cache_get_field_content(i,"pluva3",b);				VehicleInfo[i][vpluva3] = strval(b);
		cache_get_field_content(i,"pluva4",b);				VehicleInfo[i][vpluva4] = strval(b);
		cache_get_field_content(i,"pluva5",b);				VehicleInfo[i][vpluva5] = strval(b);
		cache_get_field_content(i,"pluva1a",b);				VehicleInfo[i][vpluva1a] = strval(b);
		cache_get_field_content(i,"pluva2a",b);				VehicleInfo[i][vpluva2a] = strval(b);
		cache_get_field_content(i,"pluva3a",b);				VehicleInfo[i][vpluva3a] = strval(b);
		cache_get_field_content(i,"pluva4a",b);				VehicleInfo[i][vpluva4a] = strval(b);
		cache_get_field_content(i,"pluva5a",b);				VehicleInfo[i][vpluva5a] = strval(b);
		cache_get_field_content(i,"pluva1t",b);				VehicleInfo[i][vpluva1t] = strval(b);
		cache_get_field_content(i,"pluva2t",b);				VehicleInfo[i][vpluva2t] = strval(b);
		cache_get_field_content(i,"pluva3t",b);				VehicleInfo[i][vpluva3t] = strval(b);
		cache_get_field_content(i,"pluva4t",b);				VehicleInfo[i][vpluva4t] = strval(b);
		cache_get_field_content(i,"pluva5t",b);				VehicleInfo[i][vpluva5t] = strval(b);

		cache_get_field_content(i,"Slot1X",b);				VehicleInfo[i][Slot1X] = floatstr(b);
		cache_get_field_content(i,"Slot1Y",b);				VehicleInfo[i][Slot1Y] = floatstr(b);
		cache_get_field_content(i,"Slot1Z",b);				VehicleInfo[i][Slot1Z] = floatstr(b);
		cache_get_field_content(i,"Slot1RX",b);				VehicleInfo[i][Slot1RX] = floatstr(b);
		cache_get_field_content(i,"Slot1RY",b);				VehicleInfo[i][Slot1RY] = floatstr(b);
		cache_get_field_content(i,"Slot1RZ",b);				VehicleInfo[i][Slot1RZ] = floatstr(b);
		cache_get_field_content(i,"Slot2X",b);				VehicleInfo[i][Slot2X] = floatstr(b);
		cache_get_field_content(i,"Slot2Y",b);				VehicleInfo[i][Slot2Y] = floatstr(b);
		cache_get_field_content(i,"Slot2Z",b);				VehicleInfo[i][Slot2Z] = floatstr(b);
		cache_get_field_content(i,"Slot2RX",b);				VehicleInfo[i][Slot2RX] = floatstr(b);
		cache_get_field_content(i,"Slot2RY",b);				VehicleInfo[i][Slot2RY] = floatstr(b);
		cache_get_field_content(i,"Slot2RZ",b);				VehicleInfo[i][Slot2RZ] = floatstr(b);
		cache_get_field_content(i,"Slot3X",b);				VehicleInfo[i][Slot3X] = floatstr(b);
		cache_get_field_content(i,"Slot3Y",b);				VehicleInfo[i][Slot3Y] = floatstr(b);
		cache_get_field_content(i,"Slot3Z",b);				VehicleInfo[i][Slot3Z] = floatstr(b);
		cache_get_field_content(i,"Slot3RX",b);				VehicleInfo[i][Slot3RX] = floatstr(b);
		cache_get_field_content(i,"Slot3RY",b);				VehicleInfo[i][Slot3RY] = floatstr(b);
		cache_get_field_content(i,"Slot3RZ",b);				VehicleInfo[i][Slot3RZ] = floatstr(b);
		cache_get_field_content(i,"Slot4X",b);				VehicleInfo[i][Slot4X] = floatstr(b);
		cache_get_field_content(i,"Slot4Y",b);				VehicleInfo[i][Slot4Y] = floatstr(b);
		cache_get_field_content(i,"Slot4Z",b);				VehicleInfo[i][Slot4Z] = floatstr(b);
		cache_get_field_content(i,"Slot4RX",b);				VehicleInfo[i][Slot4RX] = floatstr(b);
		cache_get_field_content(i,"Slot4RY",b);				VehicleInfo[i][Slot4RY] = floatstr(b);
		cache_get_field_content(i,"Slot4RZ",b);				VehicleInfo[i][Slot4RZ] = floatstr(b);
		cache_get_field_content(i,"Slot5X",b);				VehicleInfo[i][Slot5X] = floatstr(b);
		cache_get_field_content(i,"Slot5Y",b);				VehicleInfo[i][Slot5Y] = floatstr(b);
		cache_get_field_content(i,"Slot5Z",b);				VehicleInfo[i][Slot5Z] = floatstr(b);
		cache_get_field_content(i,"Slot5RX",b);				VehicleInfo[i][Slot5RX] = floatstr(b);
		cache_get_field_content(i,"Slot5RY",b);				VehicleInfo[i][Slot5RY] = floatstr(b);
		cache_get_field_content(i,"Slot5RZ",b);				VehicleInfo[i][Slot5RZ] = floatstr(b);
		cache_get_field_content(i,"Slot6X",b);				VehicleInfo[i][Slot6X] = floatstr(b);
		cache_get_field_content(i,"Slot6Y",b);				VehicleInfo[i][Slot6Y] = floatstr(b);
		cache_get_field_content(i,"Slot6Z",b);				VehicleInfo[i][Slot6Z] = floatstr(b);
		cache_get_field_content(i,"Slot6RX",b);				VehicleInfo[i][Slot6RX] = floatstr(b);
		cache_get_field_content(i,"Slot6RY",b);				VehicleInfo[i][Slot6RY] = floatstr(b);
		cache_get_field_content(i,"Slot6RZ",b);				VehicleInfo[i][Slot6RZ] = floatstr(b);
		cache_get_field_content(i,"Slot7X",b);				VehicleInfo[i][Slot7X] = floatstr(b);
		cache_get_field_content(i,"Slot7Y",b);				VehicleInfo[i][Slot7Y] = floatstr(b);
		cache_get_field_content(i,"Slot7Z",b);				VehicleInfo[i][Slot7Z] = floatstr(b);
		cache_get_field_content(i,"Slot7RX",b);				VehicleInfo[i][Slot7RZ] = floatstr(b);
		cache_get_field_content(i,"Slot7RY",b);				VehicleInfo[i][Slot7RY] = floatstr(b);
		cache_get_field_content(i,"Slot7RZ",b);				VehicleInfo[i][Slot7RZ] = floatstr(b);
		cache_get_field_content(i,"Slot8X",b);				VehicleInfo[i][Slot8X] = floatstr(b);
		cache_get_field_content(i,"Slot8Y",b);				VehicleInfo[i][Slot8Y] = floatstr(b);
		cache_get_field_content(i,"Slot8Z",b);				VehicleInfo[i][Slot8Z] = floatstr(b);
		cache_get_field_content(i,"Slot8RX",b);				VehicleInfo[i][Slot8RX] = floatstr(b);
		cache_get_field_content(i,"Slot8RY",b);				VehicleInfo[i][Slot8RY] = floatstr(b);
		cache_get_field_content(i,"Slot8RZ",b);				VehicleInfo[i][Slot8RZ] = floatstr(b);
		cache_get_field_content(i,"Slot9X",b);				VehicleInfo[i][Slot9X] = floatstr(b);
		cache_get_field_content(i,"Slot9Y",b);				VehicleInfo[i][Slot9Y] = floatstr(b);
		cache_get_field_content(i,"Slot9Z",b);				VehicleInfo[i][Slot9Z] = floatstr(b);
		cache_get_field_content(i,"Slot9RX",b);				VehicleInfo[i][Slot9RX] = floatstr(b);
		cache_get_field_content(i,"Slot9RY",b);				VehicleInfo[i][Slot9RY] = floatstr(b);
		cache_get_field_content(i,"Slot9RZ",b);				VehicleInfo[i][Slot9RZ] = floatstr(b);
		cache_get_field_content(i,"Slot10X",b);				VehicleInfo[i][Slot10X] = floatstr(b);
		cache_get_field_content(i,"Slot10Y",b);				VehicleInfo[i][Slot10Y] = floatstr(b);
		cache_get_field_content(i,"Slot10Z",b);				VehicleInfo[i][Slot10Z] = floatstr(b);
		cache_get_field_content(i,"Slot10RX",b);			VehicleInfo[i][Slot10RX] = floatstr(b);
		cache_get_field_content(i,"Slot10RY",b);			VehicleInfo[i][Slot10RY] = floatstr(b);
		cache_get_field_content(i,"Slot10RZ",b);			VehicleInfo[i][Slot10RZ] = floatstr(b);
	 	cache_get_field_content(i,"vSpoiler",b);				VehicleInfo[i][vSpoiler] = strval(b);
	  	cache_get_field_content(i,"vHood",b);					VehicleInfo[i][vHood] = strval(b);
	   	cache_get_field_content(i,"vRoof",b);					VehicleInfo[i][vRoof] = strval(b);
	    cache_get_field_content(i,"vSkirt",b);					VehicleInfo[i][vSkirt] = strval(b);
	    cache_get_field_content(i,"vLamps",b);					VehicleInfo[i][vLamps] = strval(b);
	    cache_get_field_content(i,"vNitro",b);					VehicleInfo[i][vNitro] = strval(b);
	    cache_get_field_content(i,"vExhaust",b);				VehicleInfo[i][vExhaust] = strval(b);
	    cache_get_field_content(i,"vWheels",b);					VehicleInfo[i][vWheels] = strval(b);
	    cache_get_field_content(i,"vStereo",b);					VehicleInfo[i][vStereo] = strval(b);
	    cache_get_field_content(i,"vHydraulics",b);				VehicleInfo[i][vHydraulics] = strval(b);
	    cache_get_field_content(i,"vFrontBumper",b);			VehicleInfo[i][vFrontBumper] = strval(b);
	    cache_get_field_content(i,"vRearBumper",b);				VehicleInfo[i][vRearBumper] = strval(b);
	    cache_get_field_content(i,"vRightVent",b);				VehicleInfo[i][vRightVent] = strval(b);
	    cache_get_field_content(i,"vLeftVent",b);				VehicleInfo[i][vLeftVent] = strval(b);
	    cache_get_field_content(i,"vPaintJob",b);				VehicleInfo[i][vPaintJob] = strval(b);

	    cache_get_field_content(i,"vPlacaProcurada",b);			VehicleInfo[i][vPlacaProcurada] = strval(b);
	    cache_get_field_content(i,"vGunHack",b);				VehicleInfo[i][vGunHack] = strval(b);
	    cache_get_field_content(i,"vGunHackA",b);				VehicleInfo[i][vGunHackA] = strval(b);
	    cache_get_field_content(i,"vAjudaIni",b);				VehicleInfo[i][vAjudaIni] = strval(b);
	    cache_get_field_content(i,"vGaragem",b);				VehicleInfo[i][vGaragem] = strval(b);
	    cache_get_field_content(i,"vDesmanchado",b);			VehicleInfo[i][vDesmanchado] = strval(b);

	}
	CreateVehicles();
	printf("[CARREGADO] %d veiculos carregados.", rows);
	return 1;
}