// MDCBASE()
//============================================================================================================= [BASE]
stock MDCBASE()
{
	MDC_BASE[0] = TextDrawCreate(110.625000, 117.083312, "LD_SPAC:white");
	TextDrawLetterSize(MDC_BASE[0], 0.000000, 0.000000);
	TextDrawTextSize(MDC_BASE[0], 405.625000, 287.166778);
	TextDrawAlignment(MDC_BASE[0], 1);
	TextDrawColor(MDC_BASE[0], -1);
	TextDrawSetShadow(MDC_BASE[0], 0);
	TextDrawSetOutline(MDC_BASE[0], 0);
	TextDrawBackgroundColor(MDC_BASE[0], 255);
	TextDrawFont(MDC_BASE[0], 4);
	TextDrawSetProportional(MDC_BASE[0], 0);
	TextDrawSetShadow(MDC_BASE[0], 0);

	MDC_BASE[1] = TextDrawCreate(114.375022, 120.336982, "box");
	TextDrawLetterSize(MDC_BASE[1], 0.000000, 1.000000);
	TextDrawTextSize(MDC_BASE[1], 512.500061, 0.000000);
	TextDrawAlignment(MDC_BASE[1], 1);
	TextDrawColor(MDC_BASE[1], -1);
	TextDrawUseBox(MDC_BASE[1], 1);
	TextDrawBoxColor(MDC_BASE[1], 41215);
	TextDrawSetShadow(MDC_BASE[1], 0);
	TextDrawSetOutline(MDC_BASE[1], 0);
	TextDrawBackgroundColor(MDC_BASE[1], 41215);
	TextDrawFont(MDC_BASE[1], 1);
	TextDrawSetProportional(MDC_BASE[1], 1);
	TextDrawSetShadow(MDC_BASE[1], 0);

	MDC_BASE[2] = TextDrawCreate(183.750000, 135.750030, "box");
	TextDrawLetterSize(MDC_BASE[2], 0.000000, 29.250000);
	TextDrawTextSize(MDC_BASE[2], 180.000000, 0.000000);
	TextDrawAlignment(MDC_BASE[2], 1);
	TextDrawColor(MDC_BASE[2], -2139062017);
	TextDrawUseBox(MDC_BASE[2], 1);
	TextDrawBoxColor(MDC_BASE[2], -1061109505);
	TextDrawSetShadow(MDC_BASE[2], 0);
	TextDrawSetOutline(MDC_BASE[2], 0);
	TextDrawBackgroundColor(MDC_BASE[2], 255);
	TextDrawFont(MDC_BASE[2], 1);
	TextDrawSetProportional(MDC_BASE[2], 1);
	TextDrawSetShadow(MDC_BASE[2], 0);

	MDC_BASE[3] = TextDrawCreate(145.000000, 160.833251, "PROCURADOS");
	TextDrawLetterSize(MDC_BASE[3], 0.219999, 1.000000);
	TextDrawTextSize(MDC_BASE[3], 0.000000, 61.875000);
	TextDrawAlignment(MDC_BASE[3], 2);
	TextDrawColor(MDC_BASE[3], 255);
	TextDrawUseBox(MDC_BASE[3], 1);
	TextDrawBoxColor(MDC_BASE[3], -1061109505);
	TextDrawSetShadow(MDC_BASE[3], 0);
	TextDrawSetOutline(MDC_BASE[3], 0);
	TextDrawBackgroundColor(MDC_BASE[3], 255);
	TextDrawFont(MDC_BASE[3], 2);
	TextDrawSetProportional(MDC_BASE[3], 1);
	TextDrawSetShadow(MDC_BASE[3], 0);
	TextDrawSetSelectable(MDC_BASE[3], true);

	MDC_BASE[4] = TextDrawCreate(507.500000, 120.583343, "X");
	TextDrawLetterSize(MDC_BASE[4], 0.400000, 0.949999);
	TextDrawTextSize(MDC_BASE[4], 0.000000, 9.375000);
	TextDrawAlignment(MDC_BASE[4], 2);
	TextDrawColor(MDC_BASE[4], -1);
	TextDrawUseBox(MDC_BASE[4], 1);
	TextDrawBoxColor(MDC_BASE[4], -16776961);
	TextDrawSetShadow(MDC_BASE[4], 0);
	TextDrawSetOutline(MDC_BASE[4], 0);
	TextDrawBackgroundColor(MDC_BASE[4], 255);
	TextDrawFont(MDC_BASE[4], 1);
	TextDrawSetProportional(MDC_BASE[4], 1);
	TextDrawSetShadow(MDC_BASE[4], 0);

	MDC_BASE[5] = TextDrawCreate(113.750000, 120.216636, "");
	TextDrawLetterSize(MDC_BASE[5], 0.000000, 0.000000);
	TextDrawTextSize(MDC_BASE[5], 8.125000, 8.333330);
	TextDrawAlignment(MDC_BASE[5], 1);
	TextDrawColor(MDC_BASE[5], -1);
	TextDrawSetShadow(MDC_BASE[5], 0);
	TextDrawSetOutline(MDC_BASE[5], 0);
	TextDrawBackgroundColor(MDC_BASE[5], 41215);
	TextDrawFont(MDC_BASE[5], 5);
	TextDrawSetProportional(MDC_BASE[5], 0);
	TextDrawSetShadow(MDC_BASE[5], 0);
	TextDrawSetPreviewModel(MDC_BASE[5], 19235);
	TextDrawSetPreviewRot(MDC_BASE[5], 90.000000, 0.000000, 0.000000, 0.129999);

	MDC_BASE[6] = TextDrawCreate(145.625000, 143.333358, "TELA_INICIAL");
	TextDrawLetterSize(MDC_BASE[6], 0.250000, 1.000000);
	TextDrawTextSize(MDC_BASE[6], 0.000000, 61.250000);
	TextDrawAlignment(MDC_BASE[6], 2);
	TextDrawColor(MDC_BASE[6], 255);
	TextDrawUseBox(MDC_BASE[6], 1);
	TextDrawBoxColor(MDC_BASE[6], -1061109505);
	TextDrawSetShadow(MDC_BASE[6], 0);
	TextDrawSetOutline(MDC_BASE[6], 0);
	TextDrawBackgroundColor(MDC_BASE[6], 255);
	TextDrawFont(MDC_BASE[6], 2);
	TextDrawSetProportional(MDC_BASE[6], 1);
	TextDrawSetShadow(MDC_BASE[6], 0);
	TextDrawSetSelectable(MDC_BASE[6], true);

	MDC_BASE[7] = TextDrawCreate(145.625000, 177.749923, "CHECAR");
	TextDrawLetterSize(MDC_BASE[7], 0.250000, 1.000000);
	TextDrawTextSize(MDC_BASE[7], 0.000000, 61.250000);
	TextDrawAlignment(MDC_BASE[7], 2);
	TextDrawColor(MDC_BASE[7], 255);
	TextDrawUseBox(MDC_BASE[7], 1);
	TextDrawBoxColor(MDC_BASE[7], -1061109505);
	TextDrawSetShadow(MDC_BASE[7], 0);
	TextDrawSetOutline(MDC_BASE[7], 0);
	TextDrawBackgroundColor(MDC_BASE[7], 255);
	TextDrawFont(MDC_BASE[7], 2);
	TextDrawSetProportional(MDC_BASE[7], 1);
	TextDrawSetShadow(MDC_BASE[7], 0);
	TextDrawSetSelectable(MDC_BASE[7], true);

	MDC_BASE[8] = TextDrawCreate(145.250015, 194.083190, "LIGACOES");
	TextDrawLetterSize(MDC_BASE[8], 0.250000, 1.000000);
	TextDrawTextSize(MDC_BASE[8], 0.000000, 60.625000);
	TextDrawAlignment(MDC_BASE[8], 2);
	TextDrawColor(MDC_BASE[8], 255);
	TextDrawUseBox(MDC_BASE[8], 1);
	TextDrawBoxColor(MDC_BASE[8], -1061109505);
	TextDrawSetShadow(MDC_BASE[8], 0);
	TextDrawSetOutline(MDC_BASE[8], 0);
	TextDrawBackgroundColor(MDC_BASE[8], 255);
	TextDrawFont(MDC_BASE[8], 2);
	TextDrawSetProportional(MDC_BASE[8], 1);
	TextDrawSetShadow(MDC_BASE[8], 0);
	TextDrawSetSelectable(MDC_BASE[8], true);

	MDC_BASE[9] = TextDrawCreate(145.250015, 210.416397, "BOLO");
	TextDrawLetterSize(MDC_BASE[9], 0.250000, 1.000000);
	TextDrawTextSize(MDC_BASE[9], 0.000000, 60.625000);
	TextDrawAlignment(MDC_BASE[9], 2);
	TextDrawColor(MDC_BASE[9], 255);
	TextDrawUseBox(MDC_BASE[9], 1);
	TextDrawBoxColor(MDC_BASE[9], -1061109505);
	TextDrawSetShadow(MDC_BASE[9], 0);
	TextDrawSetOutline(MDC_BASE[9], 0);
	TextDrawBackgroundColor(MDC_BASE[9], 255);
	TextDrawFont(MDC_BASE[9], 2);
	TextDrawSetProportional(MDC_BASE[9], 1);
	TextDrawSetShadow(MDC_BASE[9], 0);
	TextDrawSetSelectable(MDC_BASE[9], true);

	MDC_BASE[10] = TextDrawCreate(124.249992, 119.248115, "Los_Santos_Police_Departament);
	TextDrawLetterSize(MDC_BASE[11], 0.276874, 1.185834);
	TextDrawAlignment(MDC_BASE[11], 1);
	TextDrawColor(MDC_BASE[11], -1);
	TextDrawSetShadow(MDC_BASE[11], 0);
	TextDrawSetOutline(MDC_BASE[11], 0);
	TextDrawBackgroundColor(MDC_BASE[11], 255);
	TextDrawFont(MDC_BASE[11], 1);
	TextDrawSetProportional(MDC_BASE[11], 1);
	TextDrawSetShadow(MDC_BASE[11], 0);

	print("[LOAD] TEXTDRAW: MDC BASE");
}
stock MDCPARTES(playerid)
{
//======================================================================================================================================= [ Pagina Liga��es ]
	MDC_LIGACOES[playerid][0] = CreatePlayerTextDraw(playerid, 193.125000, 139.250061, "Ultimas_ligacoes");
	PlayerTextDrawLetterSize(playerid,MDC_LIGACOES[playerid][0], 0.200000, 1.000000);
	PlayerTextDrawAlignment(playerid,MDC_LIGACOES[playerid][0], 1);
	PlayerTextDrawColor(playerid,MDC_LIGACOES[playerid][0], 255);
	PlayerTextDrawSetShadow(playerid,MDC_LIGACOES[playerid][0], 0);
	PlayerTextDrawSetOutline(playerid,MDC_LIGACOES[playerid][0], 0);
	PlayerTextDrawBackgroundColor(playerid,MDC_LIGACOES[playerid][0], 255);
	PlayerTextDrawFont(playerid,MDC_LIGACOES[playerid][0], 2);
	PlayerTextDrawSetProportional(playerid,MDC_LIGACOES[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid,MDC_LIGACOES[playerid][0], 0);

	MDC_LIGACOES[playerid][1] = CreatePlayerTextDraw(playerid, 195.625000, 153.249984, "1265889_-_LSPD_LS_PD_-_10:50");
	PlayerTextDrawLetterSize(playerid,MDC_LIGACOES[playerid][1], 0.200000, 1.000000);
	PlayerTextDrawTextSize(playerid,MDC_LIGACOES[playerid][1], 397.500000, 0.000000);
	PlayerTextDrawAlignment(playerid,MDC_LIGACOES[playerid][1], 1);
	PlayerTextDrawColor(playerid,MDC_LIGACOES[playerid][1], -1);
	PlayerTextDrawUseBox(playerid,MDC_LIGACOES[playerid][1], 1);
	PlayerTextDrawBoxColor(playerid,MDC_LIGACOES[playerid][1], -2147483393);
	PlayerTextDrawSetShadow(playerid,MDC_LIGACOES[playerid][1], 0);
	PlayerTextDrawSetOutline(playerid,MDC_LIGACOES[playerid][1], 0);
	PlayerTextDrawBackgroundColor(playerid,MDC_LIGACOES[playerid][1], 255);
	PlayerTextDrawFont(playerid,MDC_LIGACOES[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid,MDC_LIGACOES[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid,MDC_LIGACOES[playerid][1], 0);
	PlayerTextDrawSetSelectable(playerid,MDC_LIGACOES[playerid][1], true);

	MDC_LIGACOES[playerid][2] = CreatePlayerTextDraw(playerid, 195.625000, 168.749832, "1265889_-_LSPD_LS_PD_-_10:50");;
	PlayerTextDrawLetterSize(playerid,MDC_LIGACOES[playerid][2], 0.200000, 1.000000);
	PlayerTextDrawTextSize(playerid,MDC_LIGACOES[playerid][2], 397.500000, 0.000000);
	PlayerTextDrawAlignment(playerid,MDC_LIGACOES[playerid][2], 1);
	PlayerTextDrawColor(playerid,MDC_LIGACOES[playerid][2], -1);
	PlayerTextDrawUseBox(playerid,MDC_LIGACOES[playerid][2], 1);
	PlayerTextDrawBoxColor(playerid,MDC_LIGACOES[playerid][2], -2147483393);
	PlayerTextDrawSetShadow(playerid,MDC_LIGACOES[playerid][2], 0);
	PlayerTextDrawSetOutline(playerid,MDC_LIGACOES[playerid][2], 0);
	PlayerTextDrawBackgroundColor(playerid,MDC_LIGACOES[playerid][2], 255);
	PlayerTextDrawFont(playerid,MDC_LIGACOES[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid,MDC_LIGACOES[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid,MDC_LIGACOES[playerid][2], 0);
	PlayerTextDrawSetSelectable(playerid,MDC_LIGACOES[playerid][2], true);
//======================================================================================================================================= [ Pagina CHECAR ]

    MDC_CHECAR[playerid][0] = CreatePlayerTextDraw(playerid,193.125000, 139.250061, "NOME");
	PlayerTextDrawLetterSize(playerid,MDC_CHECAR[playerid][0], 0.200000, 1.000000);
	PlayerTextDrawTextSize(playerid,MDC_CHECAR[playerid][0], 216.875000, 0.000000);
	PlayerTextDrawAlignment(playerid,MDC_CHECAR[playerid][0], 1);
	PlayerTextDrawColor(playerid,MDC_CHECAR[playerid][0], 255);
	PlayerTextDrawUseBox(playerid,MDC_CHECAR[playerid][0], 1);
	PlayerTextDrawBoxColor(playerid,MDC_CHECAR[playerid][0], -1061109505);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR[playerid][0], 0);
	PlayerTextDrawSetOutline(playerid,MDC_CHECAR[playerid][0], 0);
	PlayerTextDrawBackgroundColor(playerid,MDC_CHECAR[playerid][0], 255);
	PlayerTextDrawFont(playerid,MDC_CHECAR[playerid][0], 2);
	PlayerTextDrawSetProportional(playerid,MDC_CHECAR[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR[playerid][0], 0);
	PlayerTextDrawSetSelectable(playerid,MDC_CHECAR[playerid][0], true);
	
	MDC_CHECAR[playerid][1] = CreatePlayerTextDraw(playerid, 223.724533, 139.250061, "PLACA");
	PlayerTextDrawLetterSize(playerid,MDC_CHECAR[playerid][1], 0.200000, 1.000000);
	PlayerTextDrawTextSize(playerid,MDC_CHECAR[playerid][1], 251.224533, 0.000000);
	PlayerTextDrawAlignment(playerid,MDC_CHECAR[playerid][1], 1);
	PlayerTextDrawColor(playerid,MDC_CHECAR[playerid][1], 255);
	PlayerTextDrawUseBox(playerid,MDC_CHECAR[playerid][1], 1);
	PlayerTextDrawBoxColor(playerid,MDC_CHECAR[playerid][1], -1061109505);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR[playerid][1], 0);
	PlayerTextDrawSetOutline(playerid,MDC_CHECAR[playerid][1], 0);
	PlayerTextDrawBackgroundColor(playerid,MDC_CHECAR[playerid][1], 255);
	PlayerTextDrawFont(playerid,MDC_CHECAR[playerid][1], 2);
	PlayerTextDrawSetProportional(playerid,MDC_CHECAR[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR[playerid][1], 0);
	PlayerTextDrawSetSelectable(playerid,MDC_CHECAR[playerid][1], true);

	MDC_CHECAR[playerid][2] = CreatePlayerTextDraw(playerid, 258.849670, 139.233398, "YuriBS_Developero");
	PlayerTextDrawLetterSize(playerid,MDC_CHECAR[playerid][2], 0.200000, 1.000000);
	PlayerTextDrawTextSize(playerid,MDC_CHECAR[playerid][2], 376.974670, 0.000000);
	PlayerTextDrawAlignment(playerid,MDC_CHECAR[playerid][2], 1);
	PlayerTextDrawColor(playerid,MDC_CHECAR[playerid][2], 255);
	PlayerTextDrawUseBox(playerid,MDC_CHECAR[playerid][2], 1);
	PlayerTextDrawBoxColor(playerid,MDC_CHECAR[playerid][2], 0xD4D6D3FF);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR[playerid][2], 0);
	PlayerTextDrawSetOutline(playerid,MDC_CHECAR[playerid][2], 0);
	PlayerTextDrawBackgroundColor(playerid,MDC_CHECAR[playerid][2], 255);
	PlayerTextDrawFont(playerid,MDC_CHECAR[playerid][2], 2);
	PlayerTextDrawSetProportional(playerid,MDC_CHECAR[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR[playerid][2], 0);
//======================================================================================================================================= [ Pagina CHECAR > PESSOA ]
    MDC_CHECAR_P[playerid][0] = CreatePlayerTextDraw(playerid,138.125000, 154.416748, "");
	PlayerTextDrawLetterSize(playerid,MDC_CHECAR_P[playerid][0], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid,MDC_CHECAR_P[playerid][0], 166.875000, 159.999877);
	PlayerTextDrawAlignment(playerid,MDC_CHECAR_P[playerid][0], 1);
	PlayerTextDrawColor(playerid,MDC_CHECAR_P[playerid][0], -1);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_P[playerid][0], 0);
	PlayerTextDrawSetOutline(playerid,MDC_CHECAR_P[playerid][0], 0);
	PlayerTextDrawBackgroundColor(playerid,MDC_CHECAR_P[playerid][0], -1);
	PlayerTextDrawFont(playerid,MDC_CHECAR_P[playerid][0], 5);
	PlayerTextDrawSetProportional(playerid,MDC_CHECAR_P[playerid][0], 0);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_P[playerid][0], 0);
	PlayerTextDrawSetPreviewModel(playerid,MDC_CHECAR_P[playerid][0], 195);
	PlayerTextDrawSetPreviewRot(playerid,MDC_CHECAR_P[playerid][0], -5.000000, 0.000000, 25.000000, 0.800000);

	MDC_CHECAR_P[playerid][1] = CreatePlayerTextDraw(playerid,185.000000, 235.499954, "box");
	PlayerTextDrawLetterSize(playerid,MDC_CHECAR_P[playerid][1], 0.000000, 12.375000);
	PlayerTextDrawTextSize(playerid,MDC_CHECAR_P[playerid][1], 316.875000, 0.000000);
	PlayerTextDrawAlignment(playerid,MDC_CHECAR_P[playerid][1], 1);
	PlayerTextDrawColor(playerid,MDC_CHECAR_P[playerid][1], -1);
	PlayerTextDrawUseBox(playerid,MDC_CHECAR_P[playerid][1], 1);
	PlayerTextDrawBoxColor(playerid,MDC_CHECAR_P[playerid][1], -1);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_P[playerid][1], 0);
	PlayerTextDrawSetOutline(playerid,MDC_CHECAR_P[playerid][1], 0);
	PlayerTextDrawBackgroundColor(playerid,MDC_CHECAR_P[playerid][1], 255);
	PlayerTextDrawFont(playerid,MDC_CHECAR_P[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid,MDC_CHECAR_P[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_P[playerid][1], 0);

	MDC_CHECAR_P[playerid][2] = CreatePlayerTextDraw(playerid,256.773925, 166.666702, "Nome:~n~Endereco:~n~Numero:~n~Penas:~n~Licencas:");
	PlayerTextDrawLetterSize(playerid,MDC_CHECAR_P[playerid][2], 0.300000, 1.000000);
	PlayerTextDrawAlignment(playerid,MDC_CHECAR_P[playerid][2], 1);
	PlayerTextDrawColor(playerid,MDC_CHECAR_P[playerid][2], 255);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_P[playerid][2], 0);
	PlayerTextDrawSetOutline(playerid,MDC_CHECAR_P[playerid][2], 0);
	PlayerTextDrawBackgroundColor(playerid,MDC_CHECAR_P[playerid][2], 255);
	PlayerTextDrawFont(playerid,MDC_CHECAR_P[playerid][2], 2);
	PlayerTextDrawSetProportional(playerid,MDC_CHECAR_P[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_P[playerid][2], 0);

	MDC_CHECAR_P[playerid][3] = CreatePlayerTextDraw(playerid,327.378234, 166.666702, "YuriBS_Developero~n~Casa_5,Ganton,Los_Santos~n~1177589~n~Preso_5_vezes~n~Motorista,_Voo,_Armas,_Caminhoneiro");
	PlayerTextDrawLetterSize(playerid,MDC_CHECAR_P[playerid][3], 0.300000, 1.000000);
	PlayerTextDrawAlignment(playerid,MDC_CHECAR_P[playerid][3], 1);
	PlayerTextDrawColor(playerid,MDC_CHECAR_P[playerid][3], -2139062017);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_P[playerid][3], 0);
	PlayerTextDrawSetOutline(playerid,MDC_CHECAR_P[playerid][3], 0);
	PlayerTextDrawBackgroundColor(playerid,MDC_CHECAR_P[playerid][3], 255);
	PlayerTextDrawFont(playerid,MDC_CHECAR_P[playerid][3], 1);
	PlayerTextDrawSetProportional(playerid,MDC_CHECAR_P[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_P[playerid][3], 0);

	MDC_CHECAR_P[playerid][4] = CreatePlayerTextDraw(playerid,193.750000, 236.666625, "ESSA_PESSOA_TEM_MAIS_DE_UMA_CASA,_CLIQUE_AQUI_PARA_VER_A_LISTA");
	PlayerTextDrawLetterSize(playerid,MDC_CHECAR_P[playerid][4], 0.200000, 1.200000);
	PlayerTextDrawTextSize(playerid,MDC_CHECAR_P[playerid][4], 488.750000, 0.000000);
	PlayerTextDrawAlignment(playerid,MDC_CHECAR_P[playerid][4], 1);
	PlayerTextDrawColor(playerid,MDC_CHECAR_P[playerid][4], 255);
	PlayerTextDrawUseBox(playerid,MDC_CHECAR_P[playerid][4], 1);
	PlayerTextDrawBoxColor(playerid,MDC_CHECAR_P[playerid][4], -65281);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_P[playerid][4], 0);
	PlayerTextDrawSetOutline(playerid,MDC_CHECAR_P[playerid][4], 0);
	PlayerTextDrawBackgroundColor(playerid,MDC_CHECAR_P[playerid][4], 255);
	PlayerTextDrawFont(playerid,MDC_CHECAR_P[playerid][4], 2);
	PlayerTextDrawSetProportional(playerid,MDC_CHECAR_P[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_P[playerid][4], 0);
	PlayerTextDrawSetSelectable(playerid,MDC_CHECAR_P[playerid][4], true);

	MDC_CHECAR_P[playerid][5] = CreatePlayerTextDraw(playerid,193.750000, 254.666351, "essa pessoa esta na lista de procurados, clique aqui para saber mais");
	PlayerTextDrawLetterSize(playerid,MDC_CHECAR_P[playerid][5], 0.180000, 1.200000);
	PlayerTextDrawTextSize(playerid,MDC_CHECAR_P[playerid][5], 488.750000, 0.000000);
	PlayerTextDrawAlignment(playerid,MDC_CHECAR_P[playerid][5], 1);
	PlayerTextDrawColor(playerid,MDC_CHECAR_P[playerid][5], -1);
	PlayerTextDrawUseBox(playerid,MDC_CHECAR_P[playerid][5], 1);
	PlayerTextDrawBoxColor(playerid,MDC_CHECAR_P[playerid][5], -2147483393);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_P[playerid][5], 0);
	PlayerTextDrawSetOutline(playerid,MDC_CHECAR_P[playerid][5], 0);
	PlayerTextDrawBackgroundColor(playerid,MDC_CHECAR_P[playerid][5], 255);
	PlayerTextDrawFont(playerid,MDC_CHECAR_P[playerid][5], 2);
	PlayerTextDrawSetProportional(playerid,MDC_CHECAR_P[playerid][5], 1);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_P[playerid][5], 0);
	PlayerTextDrawSetSelectable(playerid,MDC_CHECAR_P[playerid][5], true);

	MDC_CHECAR_P[playerid][6] = CreatePlayerTextDraw(playerid,193.750000, 272.267333, "Multas: 1 Pendente, 2 expiradas!!");
	PlayerTextDrawLetterSize(playerid,MDC_CHECAR_P[playerid][6], 0.180000, 1.200000);
	PlayerTextDrawTextSize(playerid,MDC_CHECAR_P[playerid][6], 488.750000, 0.000000);
	PlayerTextDrawAlignment(playerid,MDC_CHECAR_P[playerid][6], 1);
	PlayerTextDrawColor(playerid,MDC_CHECAR_P[playerid][6], -1);
	PlayerTextDrawUseBox(playerid,MDC_CHECAR_P[playerid][6], 1);
	PlayerTextDrawBoxColor(playerid,MDC_CHECAR_P[playerid][6], -2147483393);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_P[playerid][6], 0);
	PlayerTextDrawSetOutline(playerid,MDC_CHECAR_P[playerid][6], 0);
	PlayerTextDrawBackgroundColor(playerid,MDC_CHECAR_P[playerid][6], 255);
	PlayerTextDrawFont(playerid,MDC_CHECAR_P[playerid][6], 2);
	PlayerTextDrawSetProportional(playerid,MDC_CHECAR_P[playerid][6], 1);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_P[playerid][6], 0);
	PlayerTextDrawSetSelectable(playerid,MDC_CHECAR_P[playerid][6], true);

	MDC_CHECAR_P[playerid][7] = CreatePlayerTextDraw(playerid,193.750000, 289.668395, "Gerenciar licencas");
	PlayerTextDrawLetterSize(playerid,MDC_CHECAR_P[playerid][7], 0.180000, 1.200000);
	PlayerTextDrawTextSize(playerid,MDC_CHECAR_P[playerid][7], 338.750000, 0.000000);
	PlayerTextDrawAlignment(playerid,MDC_CHECAR_P[playerid][7], 1);
	PlayerTextDrawColor(playerid,MDC_CHECAR_P[playerid][7], 255);
	PlayerTextDrawUseBox(playerid,MDC_CHECAR_P[playerid][7], 1);
	PlayerTextDrawBoxColor(playerid,MDC_CHECAR_P[playerid][7], -2139062017);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_P[playerid][7], 0);
	PlayerTextDrawSetOutline(playerid,MDC_CHECAR_P[playerid][7], 0);
	PlayerTextDrawBackgroundColor(playerid,MDC_CHECAR_P[playerid][7], 255);
	PlayerTextDrawFont(playerid,MDC_CHECAR_P[playerid][7], 2);
	PlayerTextDrawSetProportional(playerid,MDC_CHECAR_P[playerid][7], 1);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_P[playerid][7], 0);
	PlayerTextDrawSetSelectable(playerid,MDC_CHECAR_P[playerid][7], true);

	MDC_CHECAR_P[playerid][8] = CreatePlayerTextDraw(playerid,193.750000, 307.069458, "Aplicar Crime");
	PlayerTextDrawLetterSize(playerid,MDC_CHECAR_P[playerid][8], 0.180000, 1.200000);
	PlayerTextDrawTextSize(playerid,MDC_CHECAR_P[playerid][8], 338.750000, 0.000000);
	PlayerTextDrawAlignment(playerid,MDC_CHECAR_P[playerid][8], 1);
	PlayerTextDrawColor(playerid,MDC_CHECAR_P[playerid][8], 255);
	PlayerTextDrawUseBox(playerid,MDC_CHECAR_P[playerid][8], 1);
	PlayerTextDrawBoxColor(playerid,MDC_CHECAR_P[playerid][8], -2139062017);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_P[playerid][8], 0);
	PlayerTextDrawSetOutline(playerid,MDC_CHECAR_P[playerid][8], 0);
	PlayerTextDrawBackgroundColor(playerid,MDC_CHECAR_P[playerid][8], 255);
	PlayerTextDrawFont(playerid,MDC_CHECAR_P[playerid][8], 2);
	PlayerTextDrawSetProportional(playerid,MDC_CHECAR_P[playerid][8], 1);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_P[playerid][8], 0);
	PlayerTextDrawSetSelectable(playerid,MDC_CHECAR_P[playerid][8], true);

	MDC_CHECAR_P[playerid][9] = CreatePlayerTextDraw(playerid,193.750000, 323.870483, "Ultimas Prisoes");
	PlayerTextDrawLetterSize(playerid,MDC_CHECAR_P[playerid][9], 0.180000, 1.200000);
	PlayerTextDrawTextSize(playerid,MDC_CHECAR_P[playerid][9], 338.750000, 0.000000);
	PlayerTextDrawAlignment(playerid,MDC_CHECAR_P[playerid][9], 1);
	PlayerTextDrawColor(playerid,MDC_CHECAR_P[playerid][9], 255);
	PlayerTextDrawUseBox(playerid,MDC_CHECAR_P[playerid][9], 1);
	PlayerTextDrawBoxColor(playerid,MDC_CHECAR_P[playerid][9], -2139062017);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_P[playerid][9], 0);
	PlayerTextDrawSetOutline(playerid,MDC_CHECAR_P[playerid][9], 0);
	PlayerTextDrawBackgroundColor(playerid,MDC_CHECAR_P[playerid][9], 255);
	PlayerTextDrawFont(playerid,MDC_CHECAR_P[playerid][9], 2);
	PlayerTextDrawSetProportional(playerid,MDC_CHECAR_P[playerid][9], 1);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_P[playerid][9], 0);
	PlayerTextDrawSetSelectable(playerid,MDC_CHECAR_P[playerid][9], true);

	MDC_CHECAR_P[playerid][10] = CreatePlayerTextDraw(playerid,416.250000, 289.453857, "Ultimos crimes");
	PlayerTextDrawLetterSize(playerid,MDC_CHECAR_P[playerid][10], 0.180000, 1.200000);
	PlayerTextDrawTextSize(playerid,MDC_CHECAR_P[playerid][10], 0.000000, 144.375000);
	PlayerTextDrawAlignment(playerid,MDC_CHECAR_P[playerid][10], 2);
	PlayerTextDrawColor(playerid,MDC_CHECAR_P[playerid][10], -1);
	PlayerTextDrawUseBox(playerid,MDC_CHECAR_P[playerid][10], 1);
	PlayerTextDrawBoxColor(playerid,MDC_CHECAR_P[playerid][10], -2139062017);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_P[playerid][10], 0);
	PlayerTextDrawSetOutline(playerid,MDC_CHECAR_P[playerid][10], 0);
	PlayerTextDrawBackgroundColor(playerid,MDC_CHECAR_P[playerid][10], 255);
	PlayerTextDrawFont(playerid,MDC_CHECAR_P[playerid][10], 2);
	PlayerTextDrawSetProportional(playerid,MDC_CHECAR_P[playerid][10], 1);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_P[playerid][10], 0);

	MDC_CHECAR_P[playerid][11] = CreatePlayerTextDraw(playerid,342.500000, 303.750000, "-_Resistencia_a_prisao~n~-_Mlk_mandado~n~-_Ser_um_barata_da_vida");
	PlayerTextDrawLetterSize(playerid,MDC_CHECAR_P[playerid][11], 0.200000, 1.000000);
	PlayerTextDrawAlignment(playerid,MDC_CHECAR_P[playerid][11], 1);
	PlayerTextDrawColor(playerid,MDC_CHECAR_P[playerid][11], 255);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_P[playerid][11], 0);
	PlayerTextDrawSetOutline(playerid,MDC_CHECAR_P[playerid][11], 0);
	PlayerTextDrawBackgroundColor(playerid,MDC_CHECAR_P[playerid][11], 255);
	PlayerTextDrawFont(playerid,MDC_CHECAR_P[playerid][11], 1);
	PlayerTextDrawSetProportional(playerid,MDC_CHECAR_P[playerid][11], 1);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_P[playerid][11], 0);
	//======================================================================================================================================= [ Pagina CHECAR > PLACA ]
	MDC_CHECAR_C[playerid][0] = CreatePlayerTextDraw(playerid,185.625000, 153.250106, "");
	PlayerTextDrawLetterSize(playerid,MDC_CHECAR_C[playerid][0], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid,MDC_CHECAR_C[playerid][0], 124.375000, 116.833221);
	PlayerTextDrawAlignment(playerid,MDC_CHECAR_C[playerid][0], 1);
	PlayerTextDrawColor(playerid,MDC_CHECAR_C[playerid][0], -1);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_C[playerid][0], 0);
	PlayerTextDrawSetOutline(playerid,MDC_CHECAR_C[playerid][0], 0);
	PlayerTextDrawBackgroundColor(playerid,MDC_CHECAR_C[playerid][0], -1);
	PlayerTextDrawFont(playerid,MDC_CHECAR_C[playerid][0], 5);
	PlayerTextDrawSetProportional(playerid,MDC_CHECAR_C[playerid][0], 0);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_C[playerid][0], 0);
	PlayerTextDrawSetPreviewModel(playerid,MDC_CHECAR_C[playerid][0], 560);
	PlayerTextDrawSetPreviewRot(playerid,MDC_CHECAR_C[playerid][0], -20.000000, 0.000000, 25.000000, 0.800000);
	PlayerTextDrawSetPreviewVehCol(playerid,MDC_CHECAR_C[playerid][0], 1, 1);

	MDC_CHECAR_C[playerid][1] = CreatePlayerTextDraw(playerid,327.500000, 177.750045, "Modelo?~n~Proprietario?~n~Placa?");
	PlayerTextDrawLetterSize(playerid,MDC_CHECAR_C[playerid][1], 0.200000, 1.000000);
	PlayerTextDrawAlignment(playerid,MDC_CHECAR_C[playerid][1], 1);
	PlayerTextDrawColor(playerid,MDC_CHECAR_C[playerid][1], 255);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_C[playerid][1], 0);
	PlayerTextDrawSetOutline(playerid,MDC_CHECAR_C[playerid][1], 0);
	PlayerTextDrawBackgroundColor(playerid,MDC_CHECAR_C[playerid][1], 255);
	PlayerTextDrawFont(playerid,MDC_CHECAR_C[playerid][1], 2);
	PlayerTextDrawSetProportional(playerid,MDC_CHECAR_C[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_C[playerid][1], 0);

	MDC_CHECAR_C[playerid][2] = CreatePlayerTextDraw(playerid,394.225372, 177.750045, "Sultan~n~YuriBS_Developero~n~PB0035");
	PlayerTextDrawLetterSize(playerid,MDC_CHECAR_C[playerid][2], 0.200000, 1.000000);
	PlayerTextDrawAlignment(playerid,MDC_CHECAR_C[playerid][2], 1);
	PlayerTextDrawColor(playerid,MDC_CHECAR_C[playerid][2], -2139062017);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_C[playerid][2], 0);
	PlayerTextDrawSetOutline(playerid,MDC_CHECAR_C[playerid][2], 0);
	PlayerTextDrawBackgroundColor(playerid,MDC_CHECAR_C[playerid][2], 255);
	PlayerTextDrawFont(playerid,MDC_CHECAR_C[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid,MDC_CHECAR_C[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_C[playerid][2], 0);

	MDC_CHECAR_C[playerid][3] = CreatePlayerTextDraw(playerid,189.424774, 285.984191, "Multas?_1_multa,_2_expiradas!!");
	PlayerTextDrawLetterSize(playerid,MDC_CHECAR_C[playerid][3], 0.300000, 1.000000);
	PlayerTextDrawTextSize(playerid,MDC_CHECAR_C[playerid][3], 508.799926, 0.000000);
	PlayerTextDrawAlignment(playerid,MDC_CHECAR_C[playerid][3], 1);
	PlayerTextDrawColor(playerid,MDC_CHECAR_C[playerid][3], -1);
	PlayerTextDrawUseBox(playerid,MDC_CHECAR_C[playerid][3], 1);
	PlayerTextDrawBoxColor(playerid,MDC_CHECAR_C[playerid][3], -2147483393);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_C[playerid][3], 0);
	PlayerTextDrawSetOutline(playerid,MDC_CHECAR_C[playerid][3], 0);
	PlayerTextDrawBackgroundColor(playerid,MDC_CHECAR_C[playerid][3], 255);
	PlayerTextDrawFont(playerid,MDC_CHECAR_C[playerid][3], 1);
	PlayerTextDrawSetProportional(playerid,MDC_CHECAR_C[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_C[playerid][3], 0);

	MDC_CHECAR_C[playerid][4] = CreatePlayerTextDraw(playerid,189.549743, 269.167236, "Este veiculo esta sendo procurado!! Ver mais informacoes");
	PlayerTextDrawLetterSize(playerid,MDC_CHECAR_C[playerid][4], 0.300000, 1.000000);
	PlayerTextDrawTextSize(playerid,MDC_CHECAR_C[playerid][4], 508.924896, 0.000000);
	PlayerTextDrawAlignment(playerid,MDC_CHECAR_C[playerid][4], 1);
	PlayerTextDrawColor(playerid,MDC_CHECAR_C[playerid][4], 255);
	PlayerTextDrawUseBox(playerid,MDC_CHECAR_C[playerid][4], 1);
	PlayerTextDrawBoxColor(playerid,MDC_CHECAR_C[playerid][4], -65281);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_C[playerid][4], 0);
	PlayerTextDrawSetOutline(playerid,MDC_CHECAR_C[playerid][4], 0);
	PlayerTextDrawBackgroundColor(playerid,MDC_CHECAR_C[playerid][4], 255);
	PlayerTextDrawFont(playerid,MDC_CHECAR_C[playerid][4], 1);
	PlayerTextDrawSetProportional(playerid,MDC_CHECAR_C[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid,MDC_CHECAR_C[playerid][4], 0);
}
